config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#about'
  # get '/about' => 'welcome#about', as: '/about'
  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
  
  get '/donate' => 'treasury#donate', as: '/donate'
  post '/process_donation' => 'treasury#process_donation', as: '/processing'

  get '/proposals' => 'proposals#index', as: '/proposals'
  get '/funded' => 'proposals#funded', as: '/funded'
  get '/expired' => 'proposals#expired', as: '/expired'
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/memberships' => 'memberships#new'

  resources :users do
    resources :proposals
    resources :memberships
    resources :votes
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/membership.rb
# frozen_string_literal: true

class Membership < ApplicationRecord
  scope :active, -> { where(active: true) }
  belongs_to :user
  validates :dues, numericality: { greater_than: 10, less_than_or_equal_to: 150}
end

app/controllers/memberships_controller.rb
# frozen_string_literal: true
# extract some logic here 
class MembershipsController < ApplicationController
  include SessionsHelper
  before_action :authenticate_user, :except => [:new]

  def new
    if logged_in?
      authenticate_user
      if current_user.membership
        redirect_to edit_user_membership_path(current_user, current_user.membership)
      else
        @membership, @user = Membership.new(user_id: current_user.id), current_user
      end
    end
  end

  def destroy
    membership = current_user.membership 
    membership.active = false
    membership.save
    current_user.clear_active_vote_if_exists
    flash[:alert] = 'Successfully cancelled membership.'
    redirect_to edit_user_membership_path
  end

  def create
    @user = current_user
    @membership = @user.build_membership(membership_params)
    if @membership.save
      redirect_to edit_user_membership_path(@user, @membership)
    else
      flash[:alert] = 'There was a problem creating your membership.'
      render :new
    end
  end

  def show
    redirect_to edit_user_membership_path
  end

  def index
    redirect_to edit_user_membership_path
  end

  def edit
    @user, @membership = current_user, current_user.membership
  end

  def update
    @user, @membership = current_user, current_user.membership
    if @membership.update(membership_params.merge(active: true))
      flash[:alert] = 'Membership successfully updated.'
      redirect_to edit_user_membership_path(@user, @membership)
    else
      flash[:alert] = 'There was a problem updating your membership.'
      render :edit
    end
  end

  private

  def membership_params
    params.require(:membership).permit(:dues, :user_id)
  end
end

app/helpers/memberships_helper.rb
# frozen_string_literal: true

module MembershipsHelper
  include ApplicationHelper

  def membership_nav_link
    if current_user.try(:membership)
			link_to "Membership", edit_user_membership_path(current_user, current_user.membership)
    else
      if logged_in?
        link_to "Membership", new_user_membership_path(current_user)
      else
        link_to "Membership", '/memberships'
      end
		end
  end

  def membership_submit_button_text
    if @user.membership.try(:id)
      if @user.active_membership?
        'Update Membership'
      else
        'Renew Membership'
      end
    else
      'Create Membership'
    end
  end
end

app/views/memberships/_form.html.erb
<script>
$(document).ready(function() {

    var slider = $("#slider").slider({
        min: 10,
        max: 150,
        value: $("#membership_dues").val(),
        slide: function(event, ui) {
            $("#membership_dues").val(ui.value);
        }
    });

    $("#membership_dues").val(slider.slider("value"));
});
</script>

<p> Your membership dues are processed in real time. You may cancel your membership at any time, but your vote will only be active as long as your membership is.</p>
<%= form_for([@user, @membership]) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @membership.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<h5>Sliding-scale membership fee:</h5> 
<div class="field<%= ' field_with_errors' if @membership.errors[:dues].any? %>">
    <h4>$<%= f.number_field :dues %></h4>
</div>
<div></div>
<div id="slider"></div>
<%= f.submit membership_submit_button_text %>


<% end %>

<% if @user.active_membership? %>
	<%= button_to "Cancel Membership", user_membership_path(@user, @membership), {method: :delete, :form_class => "cancel", data: { confirm: "Really?" } }%>
<% end %>

app/views/memberships/edit.html.erb
<div class="info-box">
<%= render partial: 'form', locals: {membership: @membership}%>
</div>

app/views/memberships/new.html.erb
<div class="info-box">
<% if logged_in? %>
	<%= render partial: 'form', locals: {membership: @membership}%>
<% else %>
	<h3>Sign up for an account before creating a membership </h3>
<% end %>
</div>