config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#about'
  # get '/about' => 'welcome#about', as: '/about'
  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')
  
  get '/donate' => 'treasury#donate', as: '/donate'
  post '/process_donation' => 'treasury#process_donation', as: '/processing'

  get '/proposals' => 'proposals#index', as: '/proposals'
  get '/funded' => 'proposals#funded', as: '/funded'
  get '/expired' => 'proposals#expired', as: '/expired'
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/memberships' => 'memberships#new'

  resources :users do
    resources :proposals
    resources :memberships
    resources :votes
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proposal.rb
# frozen_string_literal: true

class Proposal < ApplicationRecord
  include SessionsHelper
  include ProposalsHelper

  belongs_to :user
  has_many :votes
  has_many :users, through: :votes
  
  scope :inactive, -> { where(active: false) }
  scope :active, -> { where(active: true) }

  validates :title, length: { minimum: 10 }
  validates :description, length: { minimum: 50 }
  validates :funding_goal, numericality: { greater_than: 1 }
  validate :expiration_cannot_be_in_the_past

  
  def expiration_cannot_be_in_the_past
    if expiration.present? && expiration < Date.today
      errors.add(:expiration, "Can't be in the past.")
    end
  end    

  def self.max_votes
    active.select { |proposal| proposal.votes.active.count == Proposal.max_vote_count }
  end

  def self.max_vote_count
    active.collect { |proposal| proposal.votes.active.count }.max
  end

  def self.deactivate_expired
    active.each do |proposal|
      if proposal.expiration < Date.today
        proposal.active = false
        proposal.save
      end
    end
  end
end

app/controllers/proposals_controller.rb
# frozen_string_literal: true

class ProposalsController < ApplicationController
  include SessionsHelper
  before_action :authenticate_user, :except => [:index, :show, :funded, :expired]

  def new
    @proposal, @user = Proposal.new, current_user
    unless params[:user_id].to_i == current_user.id
      redirect_to new_user_proposal_path(current_user)
    end
  end

  def create
    @user, @proposal = current_user, Proposal.new(proposal_params)
    if @proposal.save
      redirect_to user_proposal_path(@user, @proposal)
    else
      flash[:alert] = 'There was a problem creating your proposal.'
      render :new
    end
  end

  def index
    if params[:user_id]
      @proposals = Proposal.select{|proposal| proposal.user_id == params[:user_id].to_i }
      if @proposals.length > 1
        render :index
      elsif @proposals.length > 0
        @proposal = @proposals[0]
        render :show
      else
        render :nothing_here
      end
    else
      @proposals = Proposal.active.sort_by{|proposal| proposal.active_votes_count}.reverse
    end
  end

  def funded
    @proposals = Proposal.all.select{|proposal| proposal.funding_goal == proposal.funding}
    if !@proposals.empty?
      render :index
    else
      render :nothing_here
    end
  end

  def expired
    @proposals = Proposal.select{|proposal| proposal.expiration < Date.new }
    if !@proposals.empty?
      render :index
    else
      render :nothing_here
    end
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  private

  def proposal_params
    params.require(:proposal).permit(:title, :description, :funding_goal, :expiration, :user_id)
  end
end

app/helpers/proposals_helper.rb
# frozen_string_literal: true

module ProposalsHelper
  def active_votes_count
    active_votes.count
  end

  def active_votes
    votes.active
  end

  def active_vote?(user)
    user.active_vote_proposal_id == id
  end
  
  def proposals_dropdown_menu
    @links = [{:name => "Active", :url => "/proposals"}, {:name => "Expired", :url => '/expired'}, {:name => "Funded", :url => '/funded'}]

    if current_user
      @links << {:name => "Create Proposal", :url => new_user_proposal_path(current_user)}
      @links << {:name => "My Proposals", :url => user_proposals_path(current_user)}
    end
    render partial: '/proposals/dropdown_menu', locals: {links: @links}
  end
  # remove this method in first release
  def active_vote(user)
    user.active_vote
  end
end

app/views/proposals/_dropdown_menu.html.erb
        <% links.each do |link| %>
            <%= link_to link[:name], link[:url] %>
        <%end%>

app/views/proposals/_show.html.erb
	<div class="info-box">
		<h4><%= link_to "#{proposal.title} - #{proposal.user.name}", user_proposal_path(User.find(proposal.user_id), proposal) %></h4>
		<p>
		<%= proposal.description %>
		</p>
		<h4>Funding:</h4> <%= number_to_currency(proposal.funding) %>
		<h4>Funding Goal:</h4> <%= number_to_currency(proposal.funding_goal) %>
		<h4 class="votes">Votes: <%= proposal.active_votes_count %> </h4>
		<h4>Deadline:</h4> <%= proposal.expiration %> 

		
		<% if proposal.active_votes.any? {|vote| !!vote.comment} %>
			<div class="info-box">
			<% proposal.active_votes.each do |vote| %>
				<% if vote.comment != '' %>
					<h4><%= vote.user.name%> said: <%= vote.comment %></h4>
				<% end %>
			<% end %>
			</div>
		<% end %>
		
		<% if logged_in? && proposal.active && current_user.active_membership? %>
			<%= form_tag user_votes_path(current_user) do %>
				<%= render partial: 'votes/vote_form', locals: {proposal: proposal, user: current_user} %>
			<% end %>
		<% end %>
	</div>

app/views/proposals/index.html.erb
	<ul>
		<% @proposals.each do |proposal|%>
			<li><%= render partial: 'show', locals: { proposal: proposal } %></li>
		<% end%>
	</ul>

app/views/proposals/new.html.erb
<div class="info-box">
<%= form_for([@user, @proposal]) do |f| %>
  <% if @proposal.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors:</h2>
      <ul>
        <% @proposal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :title %>
  <div class="field<%= ' field_with_errors' if @proposal.errors[:title].any? %>">

  <%= f.text_field :title %>
  </div>

  <%= f.label :funding_goal %>
  <div class="field<%= ' field_with_errors' if @proposal.errors[:funding_goal].any? %>">
    <%= f.number_field :funding_goal %>
  </div>
  
  <%= f.label :description %>
  <div class="field<%= ' field_with_errors' if @proposal.errors[:description].any? %>">
    <%= f.text_area :description, size: "45x15"%>
  </div>


  <div class="field<%= ' field_with_errors' if @proposal.errors[:expiration_date].any? %>">
    <%= f.label :expiration_date %>
    <%= f.date_field :expiration%>
  </div>

	<%= f.hidden_field :user_id, :value => @user.id %>

  <%= f.submit "Submit" %>

  <% end %>
</div>

app/views/proposals/nothing_here.html.erb
<h1>There's nothing here. </h1>

app/views/proposals/show.html.erb
<%= render partial: 'show', locals: {proposal: @proposal} %>

app/views/proposals/user.html.erb
<ul>
<% current_user.proposals.each do |proposal|%>
    
    <li><%= render partial: 'show', locals: { proposal: proposal } %></li>

<% end%>
</ul>